### ISSUE TITLE
could  you fix indentLine plugin 's indentLine-color ?

### ISSUE THREAD

**Issue by cybaol** [theniceboy/nvim-deus#2]
![DeepinScreenshot_select-area_20210115162658](https://user-images.githubusercontent.com/48387783/104700289-e2dafc80-574e-11eb-9e4c-0e7be9e5e774.png)

**Comment by cybaol** [comment]
my indentline configs:
let g:indentLine_setColors       = 0
let g:indentLine_setConceal      = 0
let g:indentLine_color_term      = 239
let g:indentLine_bgcolor_term    = 202
let g:indentLine_fileTypeExclude = ['dashboard', 'defx', 'tex', 'vista']

**Comment by theniceboy** [comment]
我试了一下，加上你的配置以后会变白，但去掉以后就正常了。

好久没试这个插件了，看来他们已经修复卡顿问题了。谢谢

如果还有问题可以再open这个issue
