### ISSUE TITLE
The `t_Co` options has been deprecated

### ISSUE THREAD

**Issue by Avimitin** [theniceboy/nvim-deus#4]
In the latest build of the neovim, the `t_Co` option is no more supported. The `nvim-deus` theme is also out of date because the template theme `highlite` is using `t_Co` in `deus.lua` in the old version.

I've used the new highlite template to build the deus theme which fixed the issue I described above. You can take a look at it [Avimitin/neovim-deus](https://github.com/Avimitin/neovim-deus). If you are satisfied with it, I am willing to create a new branch base on your repository and make a pull request to update the theme.

**Comment by theniceboy** [comment]
Ah! Thank you for the information! I would love a PR! Please let me know if you have any difficulties.

**Comment by tan-wei** [comment]
Now `t_Co` will complains "Unknown option 't_Co'". See [here](https://github.com/theniceboy/nvim-deus/blob/master/lua/deus.lua#L31)
